#!/bin/bash
if [ "" = "$1" ] || [ "--help" = "$1" ] ; then
    echo "Use to install a git hook in the appropriate place"
    echo
    echo "./install-git-hooks <hook-name>"
    echo
    echo "e.g. ./install-git-hooks pre-commit"
else
    cp src/git-hooks/$1 .git/hooks/
    chmod +x .git/hooks/$1
fi;
