#!/bin/env sh
branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "You can't commit directly to master branch"
  exit 1
fi

#flake8 --append-config=setup-dev.cfg src/astral
